### ISSUE TITLE
DCD support?

### ISSUE THREAD

**Issue by TurkeyMan** [dlang-vscode/dlang-vscode#1]
Just noticed this project, very exciting!
Is there intent to support DCD for autocomplete and co?

**Comment by mattiascibien** [comment]
Actually there could be options for anything.... I will look into them. You are also free to fork and add any features. I will be glad to add them :+1:

**Comment by mattiascibien** [comment]
@TurkeyMan I have just noticed DCD. Was looking for something like this. :+1:

**Comment by TurkeyMan** [comment]
Yeah, DCD is probably already installed and running on D developers pc's. It would be really cool if that worked.
I'm surprised there are no GDB plugins appeared yet. I expect debugging would be able to be a separate debugging plugin.

**Comment by mattiascibien** [comment]
@TurkeyMan I have started investigating on how to add DCD support. I will take as inspiration the [atomize-d](https://github.com/Vild/atomize-d/) plugin for atom and this seems to be quite easy. Thanks for your suggestion.

**Comment by TurkeyMan** [comment]
Awesome news, Looking forward to it! Thanks for your work :)

**Comment by mattiascibien** [comment]
@TurkeyMan you can check out #2 if you need it immediately. I want to merge it surely.

**Comment by mattiascibien** [comment]
@TurkeyMan if you clone the master branch you can help us testing the support for DCD and DFMT that we have included.
