### ISSUE TITLE
Error with hints

### ISSUE THREAD

**Issue by simonorono** [dlang-vscode/dlang-vscode#20]
The extension is giving me two invalid hints:

![screenshot at 2016-11-18 04-10-18](https://cloud.githubusercontent.com/assets/12176276/20423153/1bff940c-ad45-11e6-9531-be92afed3b5c.png)

I realize this error is from one of the third party tools this extension use. Please point me out where should I post this.

Here's the code tested:

```d
import std.algorithm: partition3;
import std.stdio: readln, writeln;

private void quicksort(T)(T[] arr) {
	if (arr.length >= 2) {
		auto p = partition3(arr, arr[0]);
		p[0].quicksort;
		p[2].quicksort;
	}
}

void main() {
	auto arr = [10, 9, 8];
	arr.quicksort;
	arr.writeln;
	readln();
}
```

**Comment by LaurentTreguier** [comment]
I'm afraid this is an upstream issue... This extension uses [Dscanner](https://github.com/Hackerpilot/Dscanner) to provide linting, so this is probably where the problem is.

**Comment by simonorono** [comment]
Thanks, an [issue](https://github.com/Hackerpilot/Dscanner/issues/378) was created for Dscanner
