### ISSUE TITLE
Extra Unused Symbols AST Dscanner

### ISSUE THREAD

**Issue by skl131313** [dlang-vscode/dlang-vscode#22]
When I look for symbols in a source file the top is flooded with types that aren't defined in the source file. This results in 20+ duplicate symbols that just point to the first line of the source file. It looks like it is using variable declaration types as symbols.

For example manually running "dscanner --ast" on a file I find the following:

```xml
<declaration>
   <variableDeclaration>
      <type pretty="Vec3">
         <type2>
            <symbol>
               <identifierOrTemplateChain>
                  <identifierOrTemplateInstance>
                     <identifier>Vec3</identifier>
                  </identifierOrTemplateInstance>
               </identifierOrTemplateChain>
            </symbol>
         </type2>
      </type>
      <declarator line="111">
         <name>position</name>
      </declarator>
   </variableDeclaration>
</declaration>
```

But when I try looking for the symbol "position", it can't find any in vscode. Which makes me think it ended up as one of the 20 Vec3 symbols.

Could potentially use the output of "ctags" rather than parsing the AST from dscanner.

**Comment by LaurentTreguier** [comment]
Can I have an example source file to reproduce the problem ?
The reason I didn't want to use ctags is because it's less flexible. Dscanner can take its input from `stdin`, while the ctags option can only use files saved on the disk.

**Comment by skl131313** [comment]
```D
// app.d

import type;

Type aa0;
Type bb1;
Type cc2;
Type dd3;
Type ee4;
Type ff5;
Type gg6;
Type hh7;
Type ii8;
Type jj9;

void main()
{
}
```

```D
// type.d

module type;

struct Type
{
    int a, b, c;
}
```

![err](https://cloud.githubusercontent.com/assets/8701667/21400127/98c1fa74-c77c-11e6-8174-61975cb12bf3.png)

**Comment by LaurentTreguier** [comment]
This issue should be fixed by [this commit](https://github.com/dlang-vscode/dlang-vscode/commit/54d9b164869c820bc0fd64818150ca590fbeaecb). I corrected the code to better choose the name to display and removed variables from the list.

**Comment by skl131313** [comment]
I don't know about completely removing variables though. At least for a struct and maybe global variables, I would want those in the symbol list.

```D
struct MyStruct
{
    // ...
    MyType vars; // want to be able to find these symbols
}
```

The problem was mostly that it wasn't using the variable name nor the correct line that it was defined.

**Comment by skl131313** [comment]
Looks to be working now, thanks for fixing it so quickly.

**Comment by LaurentTreguier** [comment]
You're welcome 😄
