### ISSUE TITLE
Allow config file for Dscanner linting

### ISSUE THREAD

**Issue by skl131313** [dlang-vscode/dlang-vscode#23]
I don't need some of the linting features and they just pollute warnings/errors window. Add an option to specify a config file location and use that, or have the process be created with a cwd set to the workspace root.  I think dscanner checks the cwd for a dscanner.ini file.

**Comment by LaurentTreguier** [comment]
[This commit](https://github.com/dlang-vscode/dlang-vscode/pull/16/commits/47f26a4cc4d9d5cc1cb93672f5f1a87454f1db1b) makes Dscanner aware of `dscanner.ini` if it's present in the workspace root.
In some future update, I think I will try to use the Code Actions to allow for quickly disabling unwanted checks
