### ISSUE TITLE
Output Window Changes Cursor Focus When Hiding.

### ISSUE THREAD

**Issue by skl131313** [dlang-vscode/dlang-vscode#25]
When vscode is opened to a workspace or file that causes the D extension to load. The output window steals/shifts focus from whatever the user was currently doing, once everything is loaded and the output window closes. If a search was being done (ctrl+shift+F) the focus is shifted away from the search edit box and to the main window. Same for the command panel (ctrl+P).

Potentially related code:
https://github.com/dlang-vscode/dlang-vscode/blob/v0.9.0/src/extension.ts#L229

**Comment by LaurentTreguier** [comment]
I just reproduced that, the focus is indeed automatically set to the main editor when the output window is closed. Removing the line you highlighted and letting the user close it is probably the most simple solution (the focus isn't really controllable as far as I know).
