### ISSUE TITLE
Allow Adding Import Paths for DCD as a Setting

### ISSUE THREAD

**Issue by skl131313** [dlang-vscode/dlang-vscode#30]
I think there's a command to add import paths, but you have to do it every time you reopen vscode. Being able to just set it as a setting for a workspace would be more convenient.

**Comment by LaurentTreguier** [comment]
Yes, there is a command and a context menu option when clicking on a directory in the explorer. I'll add some setting for it as well then

**Comment by LaurentTreguier** [comment]
Would it be of use to interpret environment variables like `$HOME` or `%USERPATH%` ?

**Comment by skl131313** [comment]
For me I just need it to import a path in the workspace directory. If it's more work then don't worry about it, Absolute paths can just be used instead, as they shouldn't need to be changed often.

**Comment by LaurentTreguier** [comment]
That's really not much more work... I think paths that are not absolute like `some/path` will simply be interpreted as relative to he current workspace.

**Comment by skl131313** [comment]
Well if it isn't that much more work then I don't see why not.
