### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by mattiascibien** [dlang-vscode/dlang-vscode#36]
Now that CI is setup on both travis and appveyor I suggest to stark thinking about writing some test code to check automatically for criticals inside our code.

Some references: https://code.visualstudio.com/docs/extensions/testing-extensions

**Comment by LaurentTreguier** [comment]
Thanks to the [complex commands](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands), it should be feasible to simply test if everything is still working. We just need to think about every case that can be encountered for each functionality.
