### ISSUE TITLE
Installer calls fetch/build when settings provide executable dependencies. 

### ISSUE THREAD

**Issue by Cody-Duncan** [dlang-vscode/dlang-vscode#38]
After defining these settings:
d.tools.dcd.client
d.tools.dcd.server
d.tools.dfmt
d.tools.dscanner
d.tools.dfix
d.tools.dProfileViewer

D language output indicates the installer attempts to build dependencies:
"
Dub fetch : dfix
Dub build : dfix
Dub fetch : d-profile-viewer
Dub build : d-profile-viewer
Found dcd (client) : dcd-client
Found dcd (server) : dcd-server
DCD : starting server...
Found dfmt : dfmt
Found dscanner : dscanner
"

If these settings are defined, these installation steps should (probably?) be skipped.

**Comment by LaurentTreguier** [comment]
What are your settings for DFix and D-Profile-Viewer ? If you have defined correct executable paths then they should show `Found [...]` like for DCD,  Dfmt and Dscanner. If you have disabled them and the extension still tries to use them... then we have a bug.

**Comment by Cody-Duncan** [comment]
My mistake. It looks like I forgot to save my settings file, so the settings were never read for valid executable paths. VSCode's "Hot Exit" feature was catching me off guard.

For dcd, dfmt, and dscanner, it looks like it located those because I had my d-workspace directory in the system path. Dfix isn't among them, hence the fetch.

Saving the settings file and reloading, I get the following.

Found dfix : C:\D\tools\dfix\bin\dfix.exe
Dub fetch : d-profile-viewer //(expected because I don't have that installed)
Dub build : d-profile-viewer
Found dcd (client) : C:\D\tools\workspace-d\bin\dcd-client.exe
Found dcd (server) : C:\D\tools\workspace-d\bin\dcd-server.exe
DCD : starting server...
Found dfmt : C:\D\tools\workspace-d\bin\dfmt.exe
Found dscanner : C:\D\tools\workspace-d\bin\dscanner.exe

![saved_dlang_vscode_settings](https://cloud.githubusercontent.com/assets/1480323/24596240/a732bdb6-17f2-11e7-8509-6c3cc7d57676.png)


Well, I hope the attached image serves as a regression of the functionality!
Close as No-Bug (or PICNIC).

**Comment by mattiascibien** [comment]
No worries. Thanks in any case.
