### ISSUE TITLE
Ligatures are displayed incorrectly for D (dlang) variadic templates

### ISSUE THREAD

**Issue by vittorioromeo** [dlang-vscode/dlang-vscode#40]
- VSCode Version: 1.13.0 insider
- OS Version: Arch Linux x64

Using the font "Fira Code", ligatures for D variadic templates are incorrectly displayed.
![screenshot from 2017-05-19 10-35-12](https://cloud.githubusercontent.com/assets/918661/26257727/fa1c0630-3c7e-11e7-8523-152de22bf4f0.png)

**Comment by LaurentTreguier** [comment]
It's not just with ligatures, I see this without them as well. There is simply no support for variadic templates in the syntax file (yet).
