### ISSUE TITLE
struct and class keywords not highlighted

### ISSUE THREAD

**Issue by rtbo** [dlang-vscode/dlang-vscode#41]
with current branch master (0e2d983f6259d4f42f6b236a6bb933e0a1a48811), `struct` and `class` keywords are not highlighted (`union` is correctly highlighted).

![image](https://cloud.githubusercontent.com/assets/3889105/26751826/04dc9d58-4843-11e7-99cd-df6840103d73.png)

**Comment by LaurentTreguier** [comment]
This seems to come from [the recent commits upstream](https://github.com/textmate/d.tmbundle/commits/master/Syntaxes/D.tmLanguage) about support for extern structs and classes. 198c33e7aad9b8acad32e994a64a864f7a2b03fc reverts pulling those commits and should fix the issue for now.

**Comment by rtbo** [comment]
It does!
Thanks for the quick fix.
