### ISSUE TITLE
User defined DUB build type specification is missing

### ISSUE THREAD

**Issue by 9il** [dlang-vscode/dlang-vscode#45]
dlang-vscode allows to choose only predefined build types like "debug"

**Comment by LaurentTreguier** [comment]
Yes, for now only default configurations can be selected. For user-defined build specifications to work, the `dub.json` or `dub.sdl` file has to be parsed. JSON should be a piece of cake, however SDL will probably be harder to handle

**Comment by LaurentTreguier** [comment]
Actually I just remembered that I already encountered that problem, but `dub convert` can convert a `dub.sdl` file into a `dub.json` file, so copying `dub.sdl` to a temporary location and converting it solves the problem
