### ISSUE TITLE
Custom Paths for Executables

### ISSUE THREAD

**Issue by mattiascibien** [dlang-vscode/dlang-vscode#5]
We need to have configurations for those settings:
- DUB
- DCD (eventually)

They shoudl live in their own namespace. Proposed is d so the config json will be like:

``` json
"d": {
    "dub": "C:\\hello\\dub.exe"
    //others
}
```

@LaurentTreguier what do you think?

**Comment by LaurentTreguier** [comment]
It looks fine, however would it be really useful to have a path for DCD ? The way it's managed right now is using the DCD dub package, so as long as the `dub` executable is found, DCD will be usable as well.

**Comment by mattiascibien** [comment]
Maybe we should keep dub the only way as with the new feature of dub project management.
