### ISSUE TITLE
Change the path from dmd to rdmd on linux

### ISSUE THREAD

**Issue by TritiatedWater** [dlang-vscode/dlang-vscode#50]
Hi, i want to use rdmd instead of dmd.
Is that possible using it without the terminal?
Thanks.

**Comment by LaurentTreguier** [comment]
What exactly do you mean ? Dmd is not used by the extension directly, only the dub command is used.

**Comment by TritiatedWater** [comment]
So you're saying that dub is responsible to call dmd?

Is there any way to make dub execute rdmd instead of plain dmd?

Dlang also has an intrepeter (rdmd) so l can edit-run faster.

**Comment by LaurentTreguier** [comment]
If you use the tasks created with the `Create default tasks` command, you can modify the build subtask and add `"args": ["--rdmd"],` right under `"taskname": "build",` to make dub use rdmd.

**Comment by TritiatedWater** [comment]
It seems that VSCode is ignoring the `tasks.json`.

The dub args in tasks.json:
`"taskName": "build",`
`"args": ["--rdmd"],`
`"isBuildCommand": true,`

The output:
`[Running] cd "/home/abc/Documents/Projects/usless/src/" && dmd main.d && "/home/abc/Documents/Projects/usless/src/"main`
`fadsf`
`[Done] exited with code=0 in 0.596 seconds`
Or is there something I did wrong?

**Comment by LaurentTreguier** [comment]
It looks like you might be using an extension that runs the current file as a script... That doesn't look like an output from dub. If this is the case, you might as well open an issue for this extension, using `rdmd` would make a lot more sense to quickly run scripts.

**Comment by TritiatedWater** [comment]
It turns out I was using Code Runner. Just realised after you mentioned extension.
Anyway, configuring Code Runner to run rdmd also works.

Sorry for wasting your time :)

**Comment by LaurentTreguier** [comment]
No problem 👍
